/**
 * Deletes feedback rows generated by the old /api/seed/mock-feedback endpoint
 * (patient names like "Demo Patient 0-3").
 *
 * Run from backend: npm run clean-mock
 */
import dotenv from "dotenv";
import mongoose from "mongoose";
import { fileURLToPath } from "url";
import path from "path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.join(__dirname, "..", ".env") });

const MONGODB_URI =
  process.env.MONGODB_URI || "mongodb://localhost:27017/feedbacksystem";

const feedbackSchema = new mongoose.Schema(
  {
    patientName: { type: String, required: true, trim: true },
    department: { type: String, default: "", trim: true },
    rating: { type: Number, required: true, min: 1, max: 5 },
    comments: { type: String, default: "", trim: true },
    status: {
      type: String,
      enum: ["New", "In Progress", "Resolved"],
      default: "New",
    },
    source: {
      type: String,
      enum: ["patient", "staff", "ai"],
      default: "patient",
    },
    complaintSignature: { type: String, default: "", index: true },
    ticketId: { type: String, default: null, index: true },
    aiSentiment: {
      type: String,
      enum: ["positive", "neutral", "negative"],
      default: null,
    },
    aiUrgency: {
      type: String,
      enum: ["low", "medium", "high"],
      default: null,
    },
    aiTopics: { type: [String], default: [] },
    aiSummary: { type: String, default: "" },
    aiAnalyzedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

const Feedback =
  mongoose.models.Feedback || mongoose.model("Feedback", feedbackSchema);

async function main() {
  await mongoose.connect(MONGODB_URI);

  const filter = { patientName: /^Demo Patient /i };
  const before = await Feedback.countDocuments(filter);
  const result = await Feedback.deleteMany(filter);

  await mongoose.disconnect();

  console.log(
    `Removed ${result.deletedCount} mock feedback row(s) (matched ${before} before delete).`
  );
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
