/** Seed hospital departments (visit / EMR labels). */
export const SEED_DEPARTMENTS = [
  { name: "Emergency", description: "24/7 emergency and trauma" },
  { name: "General Medicine", description: "OPD and general wards" },
  { name: "Cardiology", description: "Heart and cardiac care" },
  { name: "Neurology", description: "Brain and spine" },
  { name: "Orthopedics", description: "Bones and joints" },
  { name: "Pediatrics", description: "Children and neonates" },
  { name: "Obstetrics & Gynecology", description: "Maternity and women's health" },
  { name: "Radiology", description: "Imaging and diagnostics" },
  { name: "Laboratory", description: "Pathology and lab services" },
  { name: "ICU", description: "Critical care units" },
];

/** AI routing services (under departments on tickets). */
export const SEED_ROUTING_SERVICES = [
  { name: "House Keeping", description: "Cleaning, linen, and ward hygiene" },
  { name: "Engineering", description: "Maintenance, HVAC, and facilities" },
  { name: "Billing", description: "Charges, invoices, and payments" },
  { name: "Pharmacy", description: "Medicines and dispensing" },
  { name: "Nursing", description: "Nursing care and bedside support" },
  { name: "Food Services", description: "Patient meals and diet kitchen" },
  { name: "Security", description: "Hospital security and access" },
  { name: "Front Office", description: "Registration and reception" },
  { name: "Ambulance", description: "Transport and emergency pickup" },
  { name: "IT Support", description: "Systems and equipment support" },
];

/** Builds mock feedback rows (department + service per row). */
export function buildSeedFeedback(departmentIds) {
  const dept = (name) => name;
  const daysAgo = (n) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

  return [
    {
      patientName: "Durgaram",
      patientRegNo: "UHID-10021",
      patientEncounterType: "ip",
      department: dept("Emergency"),
      lookupDepartment: dept("Emergency"),
      service: "House Keeping",
      rating: 3,
      comments: "Room was not cleaned on time. Linen was delayed.",
      status: "New",
      source: "patient",
      aiSentiment: "negative",
      aiUrgency: "medium",
      aiSummary: "Housekeeping delay in emergency ward.",
      ticketId: "TKT-FBK-2026-0043",
      feedbackIssues: [
        {
          department: "Emergency",
          recommendedService: "House Keeping",
          issueSummary: "Delayed room cleaning and linen",
          suggestedAction: "Escalate to housekeeping supervisor",
          ticketId: "TKT-FBK-2026-0043",
        },
      ],
      createdAt: daysAgo(1),
    },
    {
      patientName: "Mr. Ganapathy",
      patientRegNo: "UHID-8842",
      patientEncounterType: "op",
      department: dept("General Medicine"),
      lookupDepartment: dept("General Medicine"),
      service: "Engineering",
      rating: 4,
      comments: "AC was noisy in the waiting area but staff were helpful.",
      status: "New",
      source: "patient",
      aiSentiment: "neutral",
      aiSummary: "Minor facilities issue; overall positive staff.",
      ticketId: "TKT-FBK-2026-0042",
      createdAt: daysAgo(5),
    },
    {
      patientName: "Priya S",
      patientRegNo: "UHID-7721",
      department: dept("Cardiology"),
      lookupDepartment: dept("Cardiology"),
      service: "Nursing",
      rating: 2,
      comments: "Long wait for nurse call bell response after procedure.",
      status: "In Progress",
      source: "patient",
      aiSentiment: "negative",
      aiUrgency: "high",
      ticketId: "TKT-FBK-2026-0041",
      feedbackIssues: [
        {
          department: "Cardiology",
          recommendedService: "Nursing",
          issueSummary: "Slow nursing response",
          suggestedAction: "Review staffing on cardiology floor",
          ticketId: "TKT-FBK-2026-0041",
        },
      ],
      createdAt: daysAgo(8),
    },
    {
      patientName: "Rajesh Kumar",
      department: dept("Emergency"),
      lookupDepartment: dept("Emergency"),
      service: "Billing",
      rating: 1,
      comments: "Wrong bill amount and rude billing desk.",
      status: "New",
      source: "patient",
      aiSentiment: "negative",
      aiUrgency: "high",
      ticketId: "TKT-FBK-2026-0040",
      feedbackIssues: [
        {
          department: "Emergency",
          recommendedService: "Billing",
          issueSummary: "Billing dispute at emergency discharge",
          suggestedAction: "Billing supervisor callback within 2 hours",
          ticketId: "TKT-FBK-2026-0040",
        },
      ],
      createdAt: daysAgo(12),
    },
    {
      patientName: "Anitha M",
      patientRegNo: "UHID-5510",
      department: dept("Pediatrics"),
      lookupDepartment: dept("Pediatrics"),
      service: "Food Services",
      rating: 5,
      comments: "Excellent care and timely meals for my child.",
      status: "Resolved",
      source: "patient",
      aiSentiment: "positive",
      ticketId: null,
      createdAt: daysAgo(3),
    },
    {
      patientName: "Vikram N",
      department: dept("Orthopedics"),
      lookupDepartment: dept("Orthopedics"),
      service: "Pharmacy",
      rating: 3,
      comments: "Medicine stock was out; had to come back next day.",
      status: "New",
      source: "patient",
      aiSentiment: "negative",
      ticketId: "TKT-FBK-2026-0039",
      createdAt: daysAgo(16),
    },
    {
      patientName: "Lakshmi Devi",
      patientRegNo: "UHID-3301",
      department: dept("Obstetrics & Gynecology"),
      lookupDepartment: dept("Obstetrics & Gynecology"),
      service: "Nursing",
      rating: 5,
      comments: "Very caring nurses during delivery. Thank you.",
      status: "Resolved",
      source: "patient",
      aiSentiment: "positive",
      createdAt: daysAgo(20),
    },
    {
      patientName: "Mohammed Ali",
      department: dept("ICU"),
      lookupDepartment: dept("ICU"),
      service: "Engineering",
      rating: 2,
      comments: "Monitor alarm kept beeping; engineer came late.",
      status: "In Progress",
      source: "patient",
      aiSentiment: "negative",
      ticketId: "TKT-FBK-2026-0038",
      createdAt: daysAgo(25),
    },
    {
      patientName: "Sangeetha R",
      department: dept("Radiology"),
      lookupDepartment: dept("Radiology"),
      service: "Front Office",
      rating: 4,
      comments: "Scan appointment was on time. Registration was smooth.",
      status: "Resolved",
      source: "patient",
      aiSentiment: "positive",
      createdAt: daysAgo(7),
    },
    {
      patientName: "Guest Patient",
      department: dept("General Medicine"),
      service: "Security",
      rating: 2,
      comments: "Parking and visitor pass process was confusing.",
      status: "New",
      source: "patient",
      aiSentiment: "negative",
      ticketId: "TKT-FBK-2026-0037",
      createdAt: daysAgo(35),
    },
    {
      patientName: "Karthik P",
      patientRegNo: "UHID-9901",
      department: dept("Laboratory"),
      lookupDepartment: dept("Laboratory"),
      service: "IT Support",
      rating: 3,
      comments: "Report not visible on patient portal for two days.",
      status: "New",
      source: "patient",
      aiSentiment: "neutral",
      ticketId: "TKT-FBK-2026-0036",
      createdAt: daysAgo(40),
    },
    {
      patientName: "Meena V",
      department: dept("Neurology"),
      lookupDepartment: dept("Neurology"),
      service: "Ambulance",
      rating: 1,
      comments: "Ambulance arrived very late for transfer.",
      status: "New",
      source: "patient",
      aiSentiment: "negative",
      aiUrgency: "high",
      ticketId: "TKT-FBK-2026-0035",
      feedbackIssues: [
        {
          department: "Neurology",
          recommendedService: "Ambulance",
          issueSummary: "Delayed ambulance for inter-hospital transfer",
          suggestedAction: "Review ambulance dispatch SLA",
          ticketId: "TKT-FBK-2026-0035",
        },
      ],
      createdAt: daysAgo(45),
    },
  ].map((row, i) => ({
    ...row,
    updatedAt: row.createdAt,
    aiAnalyzedAt: row.aiSentiment ? row.createdAt : null,
    aiTopics: [],
    complaintSignature: `${String(row.department).toLowerCase()}|${String(row.service).toLowerCase()}|${String(row.comments).slice(0, 40).toLowerCase()}`,
  }));
}
